### ISSUE TITLE
Lighthouses not found by scan

### ISSUE THREAD

**Issue by seascape** [kurotu/OVR-Lighthouse-Manager#1]
Thanks for the app. Glad to see more solutions to this problem.

Win10 x64. Currently app cannot find my three 2.0 lighthouses. Scan shows a spinning icon and then stops with no results.

I have an Asus Dark Hero VII motherboard. Its Bluetooth works with various other devices like keyboards and speakers. 

Unless there is a bug, I have three theories.
- Mobo may not support Bluetooth LE?
- There is a (very thin) wall between PC's Bluetooth antenna and the lighthouses, maybe that disrupts it?
- Maybe Steam VR needs to be running during initial setup?

Regarding theory 1, [the mobo's specs](https://rog.asus.com/us/motherboards/rog-crosshair/rog-crosshair-viii-dark-hero-model/spec/) report the Bluetooth version is v5.1. Do you know if that means it has Bluetooth LE support?

That's all I have to share so far. Thanks again for the application!

**Comment by kurotu** [comment]
Thanks for feedback.

> Mobo may not support Bluetooth LE?

Sadly I can't know. Bluetooth 4.0 and later contain two kinds of technical stack, Classic and LE. They are completely different and LE was optional at least the point of 4.0.

Please try another app to test BLE. You should see devices which name is "LHB-*" when BLE works well (You don't have to pair devices).
For example: Bluetooth LE Explorer: https://www.microsoft.com/store/productId/9N0ZTKF1QD98?ocid=pdpshare
(I just searched "bluetooth le" in the store)

Possibly if you had changed device name, please let me know. OVR Lighthouse Manager filters devices by name to accelerate scanning.

> There is a (very thin) wall between PC's Bluetooth antenna and the lighthouses, maybe that disrupts it?

Possibly but I think it's okay. I'm using lighthouses in another room from PC.

> Maybe Steam VR needs to be running during initial setup?

No. SteamVR is just used for triggering automated power management.

----

I'll try to add an option to output detailed logs also on release version in next update.

**Comment by seascape** [comment]
Thanks for response.

With that app I was able to spot two of the three base stations, though they were very shy. It seemed they only enumerated soon after a base station was plugged in, and would then disappear from the list after a moment or two.

Caught one in a screenshot:
![Clip 009131 Bluetooth LE Explorer](https://github.com/kurotu/OVR-Lighthouse-Manager/assets/1672115/5a9bbe16-3f75-4847-8b3c-e85ba3231faf)

I guess that means the PC's mobo BT implementation can see BT LE?

Regarding signal strength / wall, my phone (using the Android base station control app) can easily see all three base stations from the location where this PC is.

LMK if I can offer other data. There was someone else on Reddit [having issues](https://old.reddit.com/r/ValveIndex/comments/18pi9xk/automatically_turn_on_basestations_with_steamvr/).

**Comment by kurotu** [comment]
It seems that the motherboard supports BLE, but seems not good connectivity.
Although I'm not familiar to on-board BLE, wireless connection might be jammed by a metal PC case which surrounding the board. It would be disadvantage against to smartphone, external antennas, or USB dongles.

Here is an app I just unlocked debug logs. Logs are written to `C:\Users\USERNAME\AppData\Local\OVRLighthouseManager`. Possibly it would be helpful.
https://github.com/kurotu/OVR-Lighthouse-Manager/actions/runs/7314660100/artifacts/1133287159

**Comment by kurotu** [comment]
Lighthouses discovery is rewritten at v1.1.0. I believe that the new version can solve the issue, however I'm not sure its actual because it's strongly affected by wireless condition.

**Comment by seascape** [comment]
Hey there. Sorry to duck out on the prior troubleshooting, but the result was I couldn't make the debug build spit out new logs, for whatever reason.

Anyway, over time OVR LM mysteriously started more or less working as expected, starting with SteamVR, detecting first two, and now more commonly all three lighthouses, and spinning them up. Then sleeping them at end of session. A few times early on I still had to pull the power manually on one but lately it's been seeing them all.

Just saw there is a new version, will install now and see how that goes.

**Comment by seascape** [comment]
Continuing to function very nicely.

**Comment by kurotu** [comment]
Grad to hear that!
