### ISSUE TITLE
[Feature request]Add start this app when login Windows

### ISSUE THREAD

**Issue by AlanBacker** [kurotu/OVR-Lighthouse-Manager#4]
I really like this project and I hope you can add two options in the settings, they are:
1. Start the app when login windows
2. Minimize after start the app

**Comment by kurotu** [comment]
What's the motivation for the requests?

1. The app is automatically started **by SteamVR** once the app is installed. So I think that you don't have to configure to start the app on login.
2. In the case of 1, the app already has an option to minimize the window.

**Comment by AlanBacker** [comment]
Thanks let me know...
But I don't know if there was a bug on my Windows or something else. I tried to not open the OVR power management and turned on Steam VR, my base stations wouldn't wake up.
The only way is turn on OVR power management first and start SteamVR, My base station will wake up.
Sorry to cause you any trouble (；´д｀)ゞ

**Comment by kurotu** [comment]
Thanks to let me know. So that I think we should solve the issue rather than adding the feature.

To make sure, would you check following points?
- Reinstall the app. The installer registers the app to SteamVR as a vr overlay app.
    - `"C:\\Program Files\\OVR Lighthouse Manager\\manifest.vrmanifest"` should be included to `C:\Program Files (x86)\Steam\config\appconfig.json`.
- Whether HMD is connected. SteamVR requires a HMD to start vr overlay apps.

**Comment by AlanBacker** [comment]
After I tried reinstall the app it works!
Thank you so much!!!
